using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tarea_2
{
    class Program
    {
        static void Main(string[] args)
        {
            int A;
            int B;
            int C;
            A = 3;
            B = 5;
            C = 8;
            Console.WriteLine("Los valores iniciales de las variables son: {0} {1} y {2}", A, B, C);
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            A = 4;
            B = B + 1;
            C = 7;
            Console.WriteLine("Los nuevos valores de las variables son: {0} {1} y {2}", A, B, C);
            Console.ReadLine();
            
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            A = A + B;
            B = 9;
            C = C + 3;
            Console.WriteLine("Los valores finales de las variables en la tabla 1 son:  {0} {1} y {2}", A, B, C);
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();


            A = 5;
            B = 9;
            C = 4;
            Console.WriteLine("Los valores iniciales de las variables son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            Console.WriteLine("Los nuevos valores de las variables son: ");
            Console.ReadLine();
            A = A + 3;
            B = A;
            C = 7;
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            A = 8;
            B = 3;
            C = B + 3 + 3;
            Console.WriteLine("Los valores finales de las variables en la tabla 2 son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();


            A = 7;
            B = 5;
            C = 3;
            Console.WriteLine("Los valores iniciales de las variables son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            Console.WriteLine("Los nuevos valores de las variables son: ");
            Console.ReadLine();
            A = A + 2;
            B = B + C;
            C = 25;
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            A = A + C;
            B = 2;
            C = 8;
            Console.WriteLine("Los valores finales de las variables en la tabla 3 son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();


            A = 3;
            B = 5;
            C = 6;
            Console.WriteLine("Los valores iniciales de las variables son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            Console.WriteLine("Los nuevos valores de las variables son: ");
            Console.ReadLine();
            A = 1;
            B = B + 1;
            C = 20;
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            A = A + B;
            B = 5;
            C = C + 8;
            Console.WriteLine("Los valores finales de las variables en la tabla 4 son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();


            A = 12;
            B = 50;
            C = 3;
            Console.WriteLine("Los valores iniciales de las variables son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            Console.WriteLine("Los nuevos valores de las variables son: ");
            Console.ReadLine();
            A = 16;
            B = B + 1;
            C = 15;
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            A = A + C;
            B = 7;
            C = A + B;
            Console.WriteLine("Los valores finales de las variables en la tabla 5 son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();


            A = 30;
            B = 20;
            C = 10;
            Console.WriteLine("Los valores iniciales de las variables son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            Console.WriteLine("Los nuevos valores de las variables son: ");
            Console.ReadLine();
            A = 5;
            B = B + 5;
            C = 1;
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            A = A + A;
            B = 8;
            C = C + C;
            Console.WriteLine("Los valores finales de las variables en la tabla 6 son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();


            A = 1;
            B = 2;
            C = 3;
            Console.WriteLine("Los valores iniciales de las variables son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            Console.WriteLine("Los nuevos valores de las variables son: ");
            Console.ReadLine();
            A = 4;
            B = 5;
            C = 6;
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            A = 7;
            B = 8;
            C = 9;
            Console.WriteLine("Los valores finales de las variables en la tabla 7 son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();


            A = 4;
            B = 100;
            C = 20;
            Console.WriteLine("Los valores iniciales de las variables son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            Console.WriteLine("Los nuevos valores de las variables son: ");
            Console.ReadLine();
            A = A + 5;
            B = B + A;
            C = 14;
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            A = A + C;
            B = 9;
            C = C + A;
            Console.WriteLine("Los valores finales de las variables en la tabla 8 son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();


            A = 5;
            B = 10;
            C = 15;
            Console.WriteLine("Los valores iniciales de las variables son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            Console.WriteLine("Los nuevos valores de las variables son: ");
            Console.ReadLine();
            A = A + 9;
            B = B * A;
            C = 7;
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            A = A + B;
            B = 10;
            C = C - 3;
            Console.WriteLine("Los valores finales de las variables en la tabla 9 son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();


            A = 50;
            B = 55;
            C = 60;
            Console.WriteLine("Los valores iniciales de las variables son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            Console.WriteLine("Los nuevos valores de las variables son: ");
            Console.ReadLine();
            A = B + 45;
            B = 10;
            C = C * 1;
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
            A = A + C;
            B = 10;
            C = A + 3;
            Console.WriteLine("Los valores finales de las variables en la tabla 10 son: ");
            Console.ReadLine();
            Console.WriteLine("A = " + A);
            Console.WriteLine("B = " + B);
            Console.WriteLine("C = " + C);
            Console.ReadLine();
        }
    }
}
